--lab 3, transaction SQL
--table 1

SELECT * FROM Child

BEGIN TRANSACTION;
UPDATE Child SET height = height + 5 WHERE Id = 1;
COMMIT;

SELECT * FROM Child

BEGIN TRANSACTION;
UPDATE Child SET weight = 25.0 WHERE Id = 2;

ROLLBACK;


SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

BEGIN TRANSACTION;
UPDATE Child SET [adress] = 'ул. Новая, 10' WHERE Id = 3;

ROLLBACK;


BEGIN TRANSACTION;
SELECT weight FROM Child WHERE Id = 1;

SELECT weight FROM Child WHERE Id = 1;
COMMIT;


SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;

BEGIN TRANSACTION;
SELECT height FROM Child WHERE Id = 2;

SELECT height FROM Child WHERE Id = 2;
COMMIT;


BEGIN TRANSACTION;
SELECT * FROM Child WHERE [Id Group] = 1;

SELECT * FROM Child WHERE [Id Group] = 1;
COMMIT;



SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

BEGIN TRANSACTION;
SELECT * FROM Child WHERE weight BETWEEN 20.0 AND 22.0;

SELECT * FROM Child WHERE weight BETWEEN 20.0 AND 22.0;
COMMIT;